export const ROUTINE = {
  1: { dia: 'Lunes', grupos: ['Pecho', 'Hombro', 'Triceps'] },
  2: { dia: 'Martes', grupos: ['Espalda', 'Biceps'] },
  3: { dia: 'Miercoles', grupos: ['Pierna', 'Abdomen'] },
  4: { dia: 'Jueves', grupos: ['Pecho', 'Espalda'] },
  5: { dia: 'Viernes', grupos: ['Brazo completo'] },
  6: { dia: 'Sabado', grupos: [] },
  0: { dia: 'Domingo', grupos: [] },
}

export const EXERCISES_BY_MUSCLE = {
  Pecho: [
    'Press banca',
    'Press inclinado',
    'Press declinado',
    'Aperturas con mancuernas',
    'Aperturas en maquina',
    'Pec deck',
    'Cruce en poleas',
    'Flexiones',
  ],
  Espalda: [
    'Jalon al pecho',
    'Remo con barra',
    'Remo con mancuerna',
    'Remo en maquina',
    'Peso muerto',
    'Pullover',
    'Remo T',
  ],
  Hombro: [
    'Press militar',
    'Elevaciones frontales',
    'Elevaciones laterales',
    'Elevaciones posteriores',
    'Face pulls',
    'Press Arnold',
  ],
  Biceps: [
    'Curl con barra',
    'Curl con mancuernas',
    'Curl martillo',
    'Curl concentrado',
    'Curl en polea',
  ],
  Triceps: [
    'Extension en polea',
    'Press frances',
    'Fondos de triceps',
    'Patada de triceps',
    'Extension overhead',
  ],
  Pierna: [
    'Sentadilla',
    'Prensa',
    'Zancadas',
    'Peso muerto rumano',
    'Curl de isquios',
    'Extension de cuadriceps',
    'Elevacion de gemelos',
  ],
  Abdomen: [
    'Crunches',
    'Plancha',
    'Elevacion de piernas',
    'Russian twist',
    'Bicycle crunches',
    'Mountain climbers',
  ],
  'Brazo completo': [
    'Curl con barra',
    'Curl martillo',
    'Extension en polea',
    'Press frances',
    'Curl concentrado',
    'Fondos de triceps',
  ],
}

export const MUSCLE_COLORS = {
  Pecho: '#a855f7',
  Espalda: '#3b82f6',
  Hombro: '#f97316',
  Biceps: '#8b5cf6',
  Triceps: '#ec4899',
  Pierna: '#10b981',
  Abdomen: '#f59e0b',
  'Brazo completo': '#06b6d4',
}